import {
  DOWN_DIRECTION,
  LEFT_DIRECTION,
  RIGHT_DIRECTION,
  UP_DIRECTION,
} from "./pixi";

export const CONTRACT_DIRECTION = {
  0: DOWN_DIRECTION,
  1: RIGHT_DIRECTION,
  2: UP_DIRECTION,
  3: LEFT_DIRECTION,
};

export const DIRECTION_IN_NUMBER = {
  [DOWN_DIRECTION]: 0,
  [RIGHT_DIRECTION]: 1,
  [UP_DIRECTION]: 2,
  [LEFT_DIRECTION]: 3,
};

export const DIRECTION_OPPOSITE = {
  [DOWN_DIRECTION]: UP_DIRECTION,
  [RIGHT_DIRECTION]: LEFT_DIRECTION,
  [UP_DIRECTION]: DOWN_DIRECTION,
  [LEFT_DIRECTION]: RIGHT_DIRECTION,
};
